# Generated by Django 4.0.4 on 2022-04-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_name', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_image', models.ImageField(blank=True, help_text="<h1 style='font-size: 12px; margin-left: 12rem; color: #ce8c95;'>width:500px height:500px</h1>", null=True, upload_to='images/')),
                ('profile_image2', models.ImageField(blank=True, help_text="<h1 style='font-size: 12px; margin-left: 12rem; color: #ce8c95;'>width:500px height:500px</h1>", null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Arun Portfolio',
                'verbose_name_plural': 'Arun Portfolio',
            },
        ),
    ]
